### ISSUE TITLE
Date Formatter

### ISSUE THREAD

**Issue by JonasLiendl** [misterorora/to-do-list#28]
Erstelle einen Date Converter, der ein gegebenes Date nach belieben das Datum verändert oder zurückgibt.

**Comment by MuffinCPT** [comment]
Verständnisfrage: Soll damit ein Converter gemeint sein, der aus einem Datum und einer Eingabe ein neues Datum macht?
Bsp.:
datum("11.05.2023") + input("3d") = finalDate("14.05.2023") 

Falls nicht, dann beschreibe das Issue bitte nochmal genauer.
Danke :)

**Comment by JonasLiendl** [comment]
Wird nicht mehr benötigt, da das schon integriert ist.
