### ISSUE TITLE
Loose Kopplung zwischen Modulen

### ISSUE THREAD

**Issue by JonasLiendl** [misterorora/to-do-list#34]
Um den Anforderungen von OOP und dem Konzept der Abstraktion gerecht zu werden, wird eine loose Kopplung zwischen den einzelnen Modulen (Input/Output, Application und Persistence) benötigt.
### Aufgaben
- [x] Interface zwischen IO und Application
- [x] Interface zwischen Persistence und Application

**Comment by misterorora** [comment]
Theoretisch implementiert... nur bei Interface zwischen IO und Application unsicher...
